MovieCollectionApp.WebApp/Controllers/ListOperationsController.cs
using MovieCollectionApp.ViewModels.Models;
using MovieCollectionApp.Business;
using System.Web.Mvc;
using System.Runtime.CompilerServices;

[assembly: InternalsVisibleTo("MovieCollectionApp.UnitTests")]
namespace MovieCollectionApp.WebApp.Controllers
{
    public class ListOperationsController : Controller
    {
        public ActionResult Index()
        {
            MovieCollectionViewModel orderViewModel = DataGenerator.InitializeData();
            return View(orderViewModel);
        }

        [HttpPost]
        public ActionResult Index(MovieCollectionViewModel orderViewModel)
        {
            return View(orderViewModel);
        }
    }
}

MovieCollectionApp.WebApp/Views/ListOperations/Index.cshtml
@model MovieCollectionApp.ViewModels.Models.MovieCollectionViewModel

<div class="jumbotron">
    <div class="panel-body" id="mainForm">
        @using (Html.BeginForm("Index", "ListOperations", FormMethod.Post))
        {
            <table class="table">
                <thead>
                    <tr>
                        <th>
                            @Html.LabelFor(m => m.Id, new { @class = "control-label" }):
                        </th>
                        <th>
                            @Html.EditorFor(m => m.Id, new { @class = "form-control" })
                        </th>
                    </tr>
                    <tr>
                    </tr>
                    <tr>
                        <th>
                            @Html.Label("Name")
                        </th>
                        <th>
                            @Html.Label("Year")
                        </th>
                        <th>
                            @Html.Label("Rating")
                        </th>
                        <th>
                            @Html.Label("Seen")
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @for (var i = 0; i < Model.Categories.Count; i++)
                    {
                        <tr>
                            <th>
                                @{
                                    bool condition = i >= ViewBag.CategoryLimitCount;
                                }
                                @Html.LabelFor(c => c.Categories[i].Name):
                            </th>
                            <th>
                                @Html.TextBoxFor(c => c.Categories[i].Name, new { disabled = condition, @class = "control-label" })
                                @Html.HiddenFor(c => c.Categories[i].Name)
                            </th>
                            <th>
                                <label class="btn btn-dark">
                                    @Html.CheckBoxFor(c => c.Categories[i].Enabled, new { @checked = Model.Categories[i].Enabled, @class = "checkbox-large" })
                                    @Html.HiddenFor(c => c.Categories[i].Enabled)
                                </label>
                            </th>
                        </tr>
                        if (Model.Categories[i].Enabled)
                        {
                            for (var j = 0; j < Model.Categories[i].Movies.Count; j++)
                            {
                                <tr class="position-sticky" id="categoryToggleExternalContent">
                                    @{
                                        var conditionAttributes = (object)new { htmlAttributes = new { @class = "form-control" } };

                                    }
                                    <td>
                                        @Html.EditorFor(m => m.Categories[i].Movies[j].Name, conditionAttributes)
                                        @Html.HiddenFor(m => m.Categories[i].Movies[j].Name)
                                    </td>
                                    <td>
                                        @Html.EditorFor(m => m.Categories[i].Movies[j].Year, conditionAttributes)
                                        @Html.HiddenFor(m => m.Categories[i].Movies[j].Year)
                                    </td>
                                    <td>
                                        @Html.EditorFor(m => m.Categories[i].Movies[j].Rating, conditionAttributes)
                                        @Html.HiddenFor(m => m.Categories[i].Movies[j].Rating)
                                    </td>
                                    <td>
                                        <label class="btn btn-dark">
                                            @{
                                                object checkboxAttributes = Model.Categories[i].Movies[j].Seen ?
                                                      (object)new { htmlAttributes = new { @class = "checkbox-large", @checked = "checked" } } :
                                                      (object)new { htmlAttributes = new { @class = "checkbox-large" } };
                                            }
                                            @Html.EditorFor(m => m.Categories[i].Movies[j].Seen, checkboxAttributes)
                                        </label>
                                    </td>
                                </tr>
                            }
                        }
                        if (!Model.Categories[i].Enabled)
                        {
                            for (var j = 0; j < Model.Categories[i].Movies.Count; j++)
                            {
                                @Html.HiddenFor(m => m.Categories[i].Movies[j].Name)
                                @Html.HiddenFor(m => m.Categories[i].Movies[j].Year)
                                @Html.HiddenFor(m => m.Categories[i].Movies[j].Rating)
                                @Html.HiddenFor(m => m.Categories[i].Movies[j].Seen)
                            }
                        }
                    }
                </tbody>
                <tfoot>
                    <tr>
                        <th>
                            @Html.LabelFor(m => m.TotalSeen, new { @class = "control-label" }):
                        </th>
                        <th>
                            @Html.DisplayFor(m => m.TotalSeen, new { @class = "form-control" })
                        </th>
                        <th>
                        </th>
                        <th>
                            <input type="submit" value="Save" class="btn btn-primary" />
                        </th>
                    </tr>
                </tfoot>
            </table>
        }
    </div>
</div>

MovieCollectionApp.WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="collapse position-sticky" id="navbarToggleExternalContent">
        <nav class="navbar navbar-dark bg-dark">
            <div class="container">
                @Html.ActionLink(" Home", "Index", "ListOperations", null, new { hidefocus = "hidefocus", @class = "navbar-toggler" })
            </div>
        </nav>
    </div>
    <nav class="navbar navbar-dark bg-dark fixed-top">
        <div class="container">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            @Html.ActionLink("Home", "Index", "ListOperations", null, new { hidefocus = "hidefocus", @class = "navbar-toggler" })
        </div>
    </nav>

    <br>
    <div class="container body-content">
        @RenderBody()
        <footer class="fixed-bottom">
            <hr />
            <div class="container">
                <p>&copy; @DateTime.Now.Year - ASP.NET Application</p>
            </div>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>